# Generated by Django 5.0.4 on 2024-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('contas_do_mes', 'Contas do mes'), ('lazer', 'Lazer'), ('compras', 'Compras')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
