# Generated by Django 5.0.4 on 2024-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gasto_categoria_alter_gasto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Contas do mes', 'Contas do mes'), ('lazer', 'Lazer'), ('compras', 'Compras')], max_length=200, null=True),
        ),
    ]
